name: tilemapgen
channels:
  - pytorch
  - nvidia
  - pytorch3d-nightly
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - cuda~=11.7
  - pytorch-cuda
  - pytorch==2.0.1
  - torchvision==0.15.2
  - pytorch3d
  - pip:
    - diffusers
    - accelerate
    - huggingface-hub
    - iopath
    - numpy
    - pillow
    - safetensors
    - pyrallis
